import { readFileSync } from "node:fs";

import { describe, expect, it } from "vitest";

import { generateBarsCss } from "@/app/_bars/generate-bars-css";
import { generateGlowCss } from "@/app/_glow/generate-glow-css";

// The two computed stylesheets are committed build artifacts: the components
// `import` them so the bundler can hash, minify and cache them, which is the
// whole reason they are no longer inline <style> tags. A committed artifact can
// go stale the moment someone retunes a constant and forgets to re-run the
// generator, and the failure would be silent -- the app would keep serving the
// old glow. This is the guard. If it fails, run `pnpm --filter web codegen:css`.
//
// endsWith/startsWith rather than toEqual on purpose: these files are ~785KB and
// ~29KB, and a character diff of that is not a test report anyone can read.
const SHEETS = [
  { file: "./_glow/glow.generated.css", generate: generateGlowCss },
  { file: "./_bars/bars.generated.css", generate: generateBarsCss },
];

describe.each(SHEETS)("$file", ({ file, generate }) => {
  const disk = readFileSync(new URL(file, import.meta.url), "utf8");

  it("is marked as generated, so nobody hand-edits it", () => {
    expect(
      disk.startsWith("/* Generated by tools/write-generated-css.mjs"),
    ).toBe(true);
  });

  it("is exactly what the generator produces today", () => {
    expect(disk.endsWith(`${generate()}\n`)).toBe(true);
  });
});
